### ISSUE TITLE
Support wrappers in rendering rather than just react children

### ISSUE THREAD

**Issue by NaLLiFFuNT** [timReynolds/react-visible#2]
I liked your little component. But I'd like to add some features.
1) The first improvement
add ability to pass tagName, to users be able to any tag
for instance
```
<ul> <!-- some menu -->
  <Visible tagName="li" visible={true}>
    Some menu item
  </Visible>
  <li>
    other menu item
  <li>
</ul>
```
html  result
```
<ul> <!-- some menu -->
  <li>
    Some menu item
  </li>
  <li>
    other menu item
  <li>
</ul>
```

if you use div in this situation - browser will say that you html is invalid

2) The second improvement
if user pass an arrow function expression, Visible component shouldn't render any tag, it should render only the function result
for instance
```
<div>
 <p>
  <Visible visible={true}>
   ()=> {'Some text.'}
  </Visible>
  Some other text
 </p>
</div>
```
html  result
```
<div>
 <p>
  Some text. Some other text
 </p>
</div>
```

**Comment by NaLLiFFuNT** [comment]
Also i can provide the solution later if you like this idea too.

**Comment by timReynolds** [comment]
The great thing about this library is it's simplicity and adding more scenarios like the above creates quite a lot of complexity. 

What this aims to do is allow simple conditional rendering within JSX, if you want something more complex other libraries exist. 

Personally in both of the examples given above I'd write them as HoC. So for a component that wraps a tag;
```
const LiVisible = ({isVisible, children}) => {
  <Visible isVisible={isVisible}>
    <li>{children}</li>
  </Visible>
}
```

For the other;
```
const VisibleFunc = ({isVisible, children}) => {
  <Visible isVisible={isVisible}>
    {children()}
  </Visible>
}
```

In both of these i'd probably shy away from using {children} because you'd expect it to be a react node. Instead I'd probably add props for text and function to each.
